#SQL and Pandas Data Analysis: Employee Database

Name:Sameer SK
Student ID:iitp_aimlt_26011480

This project demonstrates how to create a synthetic employee database using SQLite and analyze it using SQL and Pandas.

Task 1: Create Database

In [50]:
import os
if os.path.exists("employees.db"):
    os.remove("employees.db")

In [51]:
import sqlite3
import pandas as pd
import random

In [52]:
#Create SQLite Database
conn = sqlite3.connect("employees.db")
cursor = conn.cursor()
print("Database created successfully")

Database created successfully

In [53]:
#Create Employees Table
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL,
    years_experience INTEGER,
    performance_score REAL
)
""")
print("Employees table created successfully")

Employees table created successfully

In [54]:
#Generate Synthetic Employee Data
departments = ["Engineering", "Sales", "Marketing", "HR", "Finance"]
employees = []
for i in range(1, 41):
    name = f"Employee_{i}"
    department = random.choice(departments)
    salary = random.randint(50000, 150000)
    years_exp = random.randint(1, 15)
    performance = round(random.uniform(1.0, 5.0), 2)
    employees.append((i, name, department, salary, years_exp, performance))

In [55]:
#Insert Employee Records
cursor.executemany("""
INSERT INTO employees VALUES (?, ?, ?, ?, ?, ?)
""", employees)
conn.commit()
print("40 employee records inserted successfully")

40 employee records inserted successfully

Task 2 – SQL Queries

Query 1: High Performing Employees

In [56]:
#This query finds employees with performance score greater than or equal to 4.0 and at least 3 years of experience. The results are sorted by performance score in descending order and limited to the top 15 employees.
query1 = """
SELECT name, department, salary, performance_score
FROM employees
WHERE performance_score >= 4.0
AND years_experience >= 3
ORDER BY performance_score DESC
LIMIT 15
"""

df_query1 = pd.read_sql(query1, conn)

df_query1

           name department    salary  performance_score
0   Employee_11      Sales   52552.0               4.86
1   Employee_23         HR  148455.0               4.77
2   Employee_37  Marketing  115148.0               4.51
3   Employee_25      Sales   56565.0               4.43
4   Employee_14         HR   69521.0               4.42
5   Employee_32  Marketing   88341.0               4.41
6   Employee_31      Sales   74423.0               4.31
7   Employee_35         HR  128850.0               4.18
8   Employee_38      Sales   92009.0               4.12
9   Employee_39      Sales  114243.0               4.11
10  Employee_18    Finance  100892.0               4.08
11  Employee_29  Marketing  116564.0               4.03

Query 2: Employees in Engineering or Sales with Salary Between 70k and 110k

In [57]:
query2 = """
SELECT *
FROM employees
WHERE salary BETWEEN 70000 AND 110000
AND department IN ('Engineering', 'Sales')
ORDER BY department ASC, salary DESC
"""

df_query2 = pd.read_sql(query2, conn)

df_query2

,emp_id,name,department,salary,years_experience,performance_score
0,7,Employee_7,Engineering,101333.0,4,1.52
1,36,Employee_36,Engineering,86861.0,8,3.47
2,6,Employee_6,Sales,109816.0,11,3.63
3,38,Employee_38,Sales,92009.0,7,4.12
4,31,Employee_31,Sales,74423.0,4,4.31

Query 3: Employee Count and Average Salary by Department

In [58]:
#This query calculates the total number of employees and the average salary for each department.  The results are sorted by average salary in descending order.
query3 = """
SELECT department,
COUNT(*) AS employee_count,
AVG(salary) AS avg_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC
"""
df_query3 = pd.read_sql(query3, conn)
df_query3

    department  employee_count     avg_salary
0           HR              11  110784.181818
1      Finance               6  106758.000000
2        Sales              10   97772.000000
3    Marketing               7   94385.857143
4  Engineering               6   79604.333333

Task 3 – Pandas Analysis

In [59]:
#Load Employee Data into Pandas
df = pd.read_sql("SELECT * FROM employees", conn)
df.head()

,emp_id,name,department,salary,years_experience,performance_score
0,1,Employee_1,Sales,141576.0,4,3.93
1,2,Employee_2,HR,115223.0,8,3.55
2,3,Employee_3,HR,137817.0,4,1.35
3,4,Employee_4,Finance,123429.0,10,3.84
4,5,Employee_5,HR,117038.0,6,2.55

In [60]:
#Average Performance Score by Department
avg_performance = df.groupby("department")["performance_score"].mean()
avg_performance

department
Engineering    2.721667
Finance        2.825000
HR             2.982727
Marketing      3.330000
Sales          3.360000
Name: performance_score, dtype: float64

In [61]:
### Replicating Query 1 Using Pandas
pandas_query1 = df.loc[
    (df["performance_score"] >= 4.0) &
    (df["years_experience"] >= 3),
    ["name", "department", "salary", "performance_score"]
].sort_values(by="performance_score", ascending=False).head(15)
pandas_query1

           name department    salary  performance_score
10  Employee_11      Sales   52552.0               4.86
22  Employee_23         HR  148455.0               4.77
36  Employee_37  Marketing  115148.0               4.51
24  Employee_25      Sales   56565.0               4.43
13  Employee_14         HR   69521.0               4.42
31  Employee_32  Marketing   88341.0               4.41
30  Employee_31      Sales   74423.0               4.31
34  Employee_35         HR  128850.0               4.18
37  Employee_38      Sales   92009.0               4.12
38  Employee_39      Sales  114243.0               4.11
17  Employee_18    Finance  100892.0               4.08
28  Employee_29  Marketing  116564.0               4.03

 #150-200 words comparing SQL vs Pandas:

SQL and Pandas are both powerful tools for data analysis, but they are used in different contexts and have different syntax styles. SQL is mainly used to query and manage data stored in relational databases. It uses commands such as `SELECT`, `WHERE`, `AND`, and `ORDER BY` to filter, sort, and retrieve data. For example, SQL uses `=` for comparison and logical operators like `AND` to combine conditions.

Pandas, on the other hand, is a Python library used for in-memory data analysis. Instead of SQL commands, Pandas uses Python syntax such as `==` for equality, `&` for combining conditions, and functions like `.sort_values()` for sorting data. Data is stored in DataFrames, which allow flexible data manipulation and analysis.

SQL is best used when working directly with large databases because it can efficiently query data stored on disk without loading everything into memory. Pandas is more suitable for detailed data exploration, transformation, and analysis once the data has been loaded into memory.

For datasets that are too large to fit into memory, SQL is the better option because the database engine processes the data internally and returns only the required results.